### ISSUE TITLE
A question about execution times of MASS

### ISSUE THREAD

**Issue by Jacks349** [TDAmeritrade/stumpy#217] opened 2020-07-23 11:25 UTC
I've been using Stumpy for a while now to detect patterns on a target dataset using a pattern specified by me, and i'm getting very good results! Step by step i'm understanding more how to find what i'm looking for, even when i'm using small dataset, so kudos to Stumpy!

The function i'm using more is `MASS`, and i am trying to understand how does it work more deeply. I hope this question is not dumb, but there is something i don't understand about how much does it take to compute the distance profile using MASS.

So here i have a very simple example:
```
def Exec():
	Pattern = [1, 13, 10, 13.4, 10.5, 12.6]

	Target = [3.92e-06, 4.02e-06, 4.02e-06, 4.02e-06, 4.02e-06, 3.95e-06, 3.99e-06, 3.96e-06, 4.03e-06, 4.32e-06, 4.33e-06, 
			4.15e-06, 4.26e-06, 4.26e-06, 4.17e-06, 4.29e-06, 4.29e-06, 4.22e-06, 4.54e-06, 4.34e-06, 5.69e-06, 5.27e-06, 
			4.99e-06, 5.9e-06, 5.53e-06, 5.71e-06, 5.3e-06, 5.48e-06, 5.29e-06, 5.48e-06, 5.23e-06, 5.35e-06, 5.15e-06, 
			6.28e-06, 5.89e-06, 6.3e-06, 5.88e-06, 5.89e-06, 6.35e-06, 6.6e-06, 6.25e-06, 6.25e-06, 6.37e-06, 6.19e-06, 
			7e-06, 6.63e-06, 7.16e-06, 6.58e-06, 6.94e-06, 6.79e-06, 6.94e-06, 6.74e-06, 6.9e-06]

	Pattern = np.array(Pattern, dtype="float32")
	Target = np.array(Target, dtype="float32")

	D1 = mass(Pattern, Target)

start = time.time()
Exec()
end = time.time()
print('ELAPSED TIME')
print(end - start)
```

The output of this function will be something around 1.68-1.71 seconds, at least for my PC. That should mean that the function took around 1.68 seconds to execute. I'm assuming that it's `mass()` taking most of the time, since i'm not doing any other computation. 

If, instead of using `mass()` only one time, i will use it more times, like below (i'm using the same data for every use of the function, but i tried to do the same with different `Pattern` arrays):

```
D1 = mass(Pattern, Target)
D1 = mass(Pattern, Target)
D1 = mass(Pattern, Target)
D1 = mass(Pattern, Target)
```

The execution time of the function will be again `1.70`. My question is the following: shouldn't the execution time be `1.68/1.70 + 1.68 + 1.68 + 1.68`, since i'm running it four times? Again, i'm sorry if i'm saying something very uncorrect here, i was just curious about this, since i'm creating a script that should use `mass()` multiple times, to check different patterns on the **same** target dataset. Thanks in advance!

**Comment by seanlaw** [comment] 2020-07-23 12:51
Closing this as this appears to be a duplicate of #218 (but please feel free to re-open if I'm wrong)

**Closed by seanlaw** 2020-07-23 12:51 UTC
