### ISSUE TITLE
Multi-dimensional Matrix Profile Analysis

### ISSUE THREAD

**Issue by samoalfred** [TDAmeritrade/stumpy#202] opened 2020-06-09 01:05 UTC
Can STUMP do multivariate data analysis? I have a dataset that has six dimensions. I want to do some analysis on location data (3D). Is this possible? If so, is there any tutorial for this? Thanks.

**Comment by seanlaw** [comment] 2020-06-09 01:43
What you may be interested in is the [`stumpy.mstump` function](https://stumpy.readthedocs.io/en/latest/api.html#stumpy.mstump) (or the distributed version `stumpy.mstumped`) which can handle multi-dimensional data. Unfortunately, a completed tutorial does not exist yet but you can take a look at this [work-in-progress](https://github.com/TDAmeritrade/stumpy/blob/master/docs/Tutorial_Multidimensional_Motif_Discovery.ipynb).

Additionally, I strongly recommend that you read [this paper by the original authors on multi-dimensional matrix profiles](https://www.cs.ucr.edu/~eamonn/Motif_Discovery_ICDM.pdf).

**Comment by seanlaw** [comment] 2020-06-14 21:44
@samoalfred Does this solve your problem?

**Comment by samoalfred** [comment] 2020-06-15 03:17
@seanlaw Thanks for this. I have not had time to look at it in details but I think it makes sense to me.

**Comment by seanlaw** [comment] 2020-06-15 18:06
@samoalfred Great. I'll close this for now but feel free to re-open it if you have any more questions!

**Closed by seanlaw** 2020-06-15 18:06 UTC
Labels: application understanding

**Comment by samoalfred** [comment] 2020-08-02 21:57
Hello Seanlaw. Does the matrix profile implemented in this Matrix Profile method use Dynamic time warping as opposed to euclidean distance? I have time series data/ trajectories that are of different length but are similar.

**Comment by seanlaw** [comment] 2020-08-02 23:57
@samoalfred No, all matrix profile implementations that I am aware of that have bee published use z-normalized Euclidean distance. I believe that there is an explicit assumption that the time points must be aligned across all of the time series.

**Comment by samoalfred** [comment] 2020-08-03 01:24
Alright thanks. I z-normalized my data before implementation with stumpy. I hope that is fine? Or does stumpy do that when I write the code?

**Comment by seanlaw** [comment] 2020-08-03 02:38
> Alright thanks. I z-normalized my data before implementation with stumpy. I hope that is fine? Or does stumpy do that when I write the code?

You'll want to feed in your raw unnormalized time series data and allow STUMPY to handle it for you. The issue is that z-normalization is performed at the subsequence level and not for the entire time series (i.e., you don't simply subtract the full time series mean and divide by the full time series stddev - this is wrong).
